name: main
on: [pull_request]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          auto-update-conda: true
          python-version: 3.9
          show-channel-urls: true
          architecture: x64
          condarc-file: .github/workflows/.condarc
          channel-priority: strict
          auto-activate-base: false
      - name: check conda channels
        shell: bash -el {0}
        run: conda config --show channels
      - name: create conda env
        shell: bash -el {0}
        run: conda env create --file=environment.yml && conda activate spokewrench
      - name: install spokewrench
        shell: bash -el {0}
        run: pip install --editable .
      - name: test install of spokewrench
        shell: bash -el {0}
        run: spokewrench -h
